# ------------------------------------------------------------------------------------- #
# DOCKER CONTAINERS              https://docs.docker.com/reference/compose-file/services/
# ------------------------------------------------------------------------------------- #
services:

# PHP FastCGI
# ----------------------------------------------------------------------- #
# ➜ https://github.com/simplicateca/docker-php-fpm
# ➜ etc/docker/php.ini
  php: &php_container
    image: simplicateca/php-fpm:8.2
    command: php-fpm
    user: "1000:1000"
    restart: no
    working_dir: /app
    volumes:
      - ./craftcms:/app
      - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./frontend/public:/app/web/dist:cached
    depends_on:
      composer:
        condition: service_completed_successfully
      redis:
        condition: service_started
      mysql:
        condition: service_healthy

# Composer (PHP Dependency Management)
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/composer
  composer:
    image: composer:2
    command: >
      sh -c 'if [ ! -f composer.lock ] || [ ! -d vendor ]; then
              composer install --verbose --no-progress --no-interaction;
            else
              echo "composer.lock and vendor/ exist, skipping install.";
            fi'
    user: "1000:1000"
    volumes:
      - ./craftcms:/app
      - ./.cache/composer:/tmp


# Craft CMS (with Queue Runner)
# ----------------------------------------------------------------------- #
# ➜ craftcms/composer.json
  craftcms:
    <<: *php_container
    command: >
      bash -c "
        ./craft setup/keys --interactive=0 &&
        ./craft install/check --interactive=0 &&
        ./craft up --interactive=0 &&
        ./craft clear-caches/all --interactive=0 &&
        ./craft queue/listen --verbose"
    stop_grace_period: "1s"
    tty: true


# MySQL 8 Database
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/mysql
# ➜ etc/mysql/seed
  mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    volumes:
      - mysql_data:/var/lib/mysql
      - ./etc/mysql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 30s
      timeout: 10s
      start_period: 20s
      start_interval: 10s
      retries: 20

# Node + ViteJS Frontend
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/node
# ➜ ./frontend/package.json
  frontend:
    image: node:lts
    command: >
      bash -c "
        [ ! -f package-lock.json ] && npm install;
        [ ! -d node_modules/.vite ] && npm ci;
        npm run dev"
    restart: no
    stop_grace_period: "1s"
    tty: true
    ports:
      - 3000:3000
    user: "1000:1000"
    working_dir: /var/www/frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/js/app.js"]
      interval: 10s
      timeout: 120s
      retries: 20
    # wait for `composer` to create the `craftcms/vendor` folder before passing it as a volume
    # otherwise, chance of permission error on `craftcms/vendor` ownership
    depends_on:
      composer:
        condition: service_completed_successfully
    volumes:
      - ./frontend:/var/www/frontend:cached
      - ./craftcms/vendor:/var/www/craftcms/vendor:ro
      - ./craftcms/templates:/var/www/craftcms/templates:ro
      - ./craftcms/modules:/var/www/craftcms/modules:ro


# Nginx Webserver
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/nginx
# ➜ etc/docker/nginx.conf
  nginx:
    image: nginx:1-alpine
    restart: no
    depends_on:
      frontend:
        condition: service_healthy
      php:
        condition: service_started
    ports:
      - 8000:80
    volumes:
      - ./craftcms/web:/app/web:ro
      - ./etc/nginx.conf:/etc/nginx/conf.d/craft.conf:ro


# Redis (Key-Value Storage)
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/redis
  redis:
    image: redis:7-alpine
    restart: no
    ports:
      - 6379:6379


# ------------------------------------------------------------------------------------- #
# CONTAINER DATA STORAGE          https://docs.docker.com/reference/compose-file/volumes/
# ------------------------------------------------------------------------------------- #
volumes:
  mysql_data:
