# ------------------------------------------------------------------------------------- #
# DOCKER CONTAINERS              https://docs.docker.com/reference/compose-file/services/
# ------------------------------------------------------------------------------------- #
services:

# Status Message (on Successful Launch)
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/busybox
# ➜ etc/docker/banner.sh
  status:
    image: busybox:latest
    command: "sh -c 'sleep 1 && /bin/sh /home/banner.sh'"
    env_file: &project_env
      - ./craftcms/.env
    volumes:
      - ./etc/banner.sh:/home/banner.sh
    depends_on:
      nginx:
        condition: service_started
      frontend:
        condition: service_healthy

# PHP FastCGI
# ----------------------------------------------------------------------- #
# ➜ https://github.com/simplicateca/docker-php-fpm
# ➜ etc/docker/php.ini
  php: &php_container
    image: simplicateca/php-fpm:8.2
    command: php-fpm
    user: "1000:1000"
    restart: no
    env_file: *project_env
    working_dir: /app
    volumes:
      - ./craftcms:/app
      - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./frontend/public:/app/web/dist:cached
    depends_on:
      composer:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

# Composer (PHP Dependency Management)
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/composer
  composer:
    image: composer:2
    command: >
      sh -c 'if [ ! -f composer.lock ] || [ ! -d vendor ]; then
              composer install --verbose --no-progress --no-interaction;
            else
              echo "composer.lock and vendor/ exist, skipping install.";
            fi'
    user: "1000:1000"
    volumes:
      - ./craftcms:/app
      - ./.cache/composer:/tmp


# Craft CMS (with Queue Runner)
# ----------------------------------------------------------------------- #
# ➜ craftcms/composer.json
# ➜ craftcms/.env
  craftcms:
    <<: *php_container
    command: >
      bash -c "
        ./craft install/check --interactive=0 &&
        ./craft setup/keys --interactive=0 &&
        ./craft up --interactive=0 &&
        ./craft clear-caches/all --interactive=0 &&
        ./craft queue/listen --verbose"
    stop_grace_period: "1s"
    tty: true
    depends_on: [php]


# MySQL 8 Database
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/mysql
# ➜ etc/docker/seed
  mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: no
    env_file: *project_env
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=${CRAFT_DB_DATABASE:-project}
      - MYSQL_USER=${CRAFT_DB_USER:-project}
      - MYSQL_PASSWORD=${CRAFT_DB_PASSWORD:-project}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./craftcms/storage/seed/:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 60s
      retries: 20


# Node + ViteJS Frontend
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/node
# ➜ ./frontend/package.json
  frontend:
    image: node:lts
    command: >
      bash -c "
        [ ! -f package-lock.json ] && npm install;
        [ ! -d node_modules/.vite ] && npm ci;
        npm run dev"
    restart: no
    stop_grace_period: "1s"
    tty: true
    ports:
      - 3000:3000
    user: "1000:1000"
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend:cached
      - ./craftcms/templates:/var/www/craftcms/templates:ro
      - ./craftcms/vendor:/var/www/craftcms/vendor:ro
      - ./craftcms/modules:/var/www/craftcms/modules:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/js/app.js"]
      interval: 10s
      timeout: 120s
      retries: 20


# Nginx Webserver
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/nginx
# ➜ etc/docker/nginx.conf
  nginx:
    image: nginx:1-alpine
    restart: no
    depends_on: [php]
    ports:
      - 8000:80
    volumes:
      - ./craftcms/web:/app/web:ro
      - ./etc/nginx.conf:/etc/nginx/conf.d/craft.conf:ro


# Redis (Key-Value Storage)
# ----------------------------------------------------------------------- #
# ➜ https://hub.docker.com/_/redis
  redis:
    image: redis:7-alpine
    restart: no
    ports:
      - 6379:6379


# ------------------------------------------------------------------------------------- #
# CONTAINER DATA STORAGE          https://docs.docker.com/reference/compose-file/volumes/
# ------------------------------------------------------------------------------------- #
volumes:
  mysql_data:
