email:
  fromEmail: craft@example.com
  fromName: English
  transportType: craft\mail\transportadapters\Sendmail
fs:
  public:
    hasUrls: true
    name: 'MinIO - Public'
    settings:
      bucket: $S3_PUBLIC_BUCKET
      endpoint: $S3_ENDPOINT
      endpointType: $S3_ENDPOINT_TYPE
      expires: ''
      keyId: $S3_ACCESS_KEY
      region: $S3_REGION
      secret: $S3_SECRET_KEY
      subfolder: $S3_PUBLIC_FOLDER
      visibility: public
    type: behinddesign\ObjectStorage\Fs
    url: '@s3Public'
  secure:
    hasUrls: false
    name: 'Minio - Secure'
    settings:
      bucket: $S3_SECURE_BUCKET
      endpoint: $S3_ENDPOINT
      endpointType: $S3_ENDPOINT_TYPE
      expires: ''
      keyId: $S3_ACCESS_KEY
      region: $S3_REGION
      secret: $S3_SECRET_KEY
      subfolder: ''
      visibility: private
    type: behinddesign\ObjectStorage\Fs
    url: null
  static:
    hasUrls: true
    name: 'MinIO - Static'
    settings:
      bucket: $S3_STATIC_BUCKET
      endpoint: $S3_ENDPOINT
      endpointType: $S3_ENDPOINT_TYPE
      expires: ''
      keyId: $S3_ACCESS_KEY
      region: $S3_REGION
      secret: $S3_SECRET_KEY
      subfolder: ''
      visibility: private
    type: behinddesign\ObjectStorage\Fs
    url: '@s3Static'