columnSuffix: null
handle: articleType
instructions: null
name: 'Article Type'
searchable: false
settings:
  configFile: ''
  configJson: "{\r\n    \"general\": \"General Article\",\r\n    \"guide\": \"Learning Guide\",\r\n    \"exclusive\": \"Digital Exclusive\",\r\n    \"audio\": \"Podcast • Audio\",\r\n    \"video\": \"Video Feature\"\r\n}"
  configTwig: ''
  customOptions: false
  mode: json
  options:
    -
      __assoc__:
        -
          - label
          - 'General Article'
        -
          - value
          - general
    -
      __assoc__:
        -
          - label
          - 'Learning Guide'
        -
          - value
          - guide
    -
      __assoc__:
        -
          - label
          - 'Digital Exclusive'
        -
          - value
          - exclusive
    -
      __assoc__:
        -
          - label
          - 'Podcast • Audio'
        -
          - value
          - audio
    -
      __assoc__:
        -
          - label
          - 'Video Feature'
        -
          - value
          - video
translationKeyFormat: null
translationMethod: none
type: simplicateca\metasettings\fields\MetaSettingsField
