# Staging Deployment Pipeline
- pipeline: "staging"
  events:
  - type: PUSH
    refs:
    - refs/heads/staging
  terminate_stale_runs: true
  clone_depth: 2
  docker_build_cache: WORKSPACE
  actions:
    # STEP 1: build the frontend js/css
    - action: "Build the frontend js/css with vite:build"
      type: "BUILD"
      working_directory: "/buddy/$BUDDY_PROJECT_NAME_ID/$BUDDY_EXECUTION_BRANCH/frontend"
      docker_image_name: "node"
      docker_image_tag: "lts"
      volume_mappings:
        - "/:/buddy/$BUDDY_PROJECT_NAME_ID/$BUDDY_EXECUTION_BRANCH"
      execute_commands:
        - "[ -f package-lock.json ] && npm ci || npm install"
        - "npm run build"

    # STEP 2: install php vendor files with composer
    - action: "Install Composer"
      type: "BUILD"
      working_directory: "/buddy/$BUDDY_PROJECT_NAME_ID/$BUDDY_EXECUTION_BRANCH/craftcms"
      docker_image_name: "composer"
      docker_image_tag: "2"
      volume_mappings:
        - "/:/buddy/$BUDDY_PROJECT_NAME_ID/$BUDDY_EXECUTION_BRANCH"
      execute_commands:
        - "composer install --verbose --no-progress --no-scripts --optimize-autoloader --no-interaction"

      # STEP 3: rsync push files to host
    - action: Rsync files to host
      type: RSYNC
      local_path: craftcms/
      delete_extra_files: true
      archive: true
      recursive: true
      compress: true
      targets:
      - target: SSH_HOST
        type: SSH
        name: $SSH_HOST
        host: $SSH_HOST
        path: $SSH_PATH/.cache
        auth:
          method: ASSETS_KEY
          username: $SSH_USER
          asset: id_workspace

      # STEP 4: create an atomic deployment release on the server
    - action: "Atomic Deployment"
      type: "SSH_COMMAND"
      shell: "BASH"
      targets:
      - target: ssh_host
        type: SSH
        name: $SSH_HOST
        host: $SSH_HOST
        path: $SSH_PATH
        auth:
          method: ASSETS_KEY
          username: $SSH_USER
          asset: id_workspace
      run_as_script: true
      working_directory: "$SSH_PATH"
      commands:
        - "rm -rf .cache/web/cpresources .env* .cache/storage"
        - "mkdir -p .cache/web/cpresources releases storage"
        - "chmod 0744 .cache/web/cpresources && chmod a+x .cache/craft"
        - "ln -nfs $SSH_PATH/.env .cache/.env"
        - "ln -nfs $SSH_PATH/storage .cache/storage"
        - "rm -rf releases/$BUDDY_EXECUTION_REVISION && cp -dR .cache releases/$BUDDY_EXECUTION_REVISION"
        - "./releases/$BUDDY_EXECUTION_REVISION/craft invalidate-tags/all --interactive=0"
        - "./releases/$BUDDY_EXECUTION_REVISION/craft clear-caches/all --interactive=0"
        - "./releases/$BUDDY_EXECUTION_REVISION/craft up --interactive=0"
        - "ln -sf releases/$BUDDY_EXECUTION_REVISION current"
        - "cd releases && ls -t | tail -n +6 | xargs rm -rf"
