defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ff76eb70-820e-4752-b138-daef62692e3f # Block Fragment
handle: reusables
maxAuthors: 1
name: Reusables
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Contextual Preview'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - 'sitehub/reusables/{{object.type.handle}}/{{object.slug}}'
propagationMethod: all
siteSettings:
  d34bee8e-bf22-451d-8339-a4342630833d: # Canada
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
