defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: bb561dd8-e748-4c68-9107-2ffd5db410d8
  -
    uid: 8b83b1c6-3917-4365-bc67-1f94599cbb08
handle: taxonomy
maxAuthors: 1
name: Taxonomies
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary URL'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  d34bee8e-bf22-451d-8339-a4342630833d:
    enabledByDefault: true
    hasUrls: true
    template: _base/entry.twig
    uriFormat: '{% import "_base/entry" as e %}{{ e.uri_format(object) }}'
structure:
  maxLevels: 2
  uid: cc00ceed-0937-472c-b55c-c83fa5fce262
type: structure
